### ISSUE TITLE
Reports (parsing) not working

### ISSUE THREAD

**Issue by MrZANE42** [TedTolboom/no.IDLock#2]
On homey fw. 1.5.5
when starting up debug and then closing door and opening the door with ID_lock 101I get this:

...
2017-11-28 23:05:02 [err] [ManagerDrivers] [IDlock101] [0] Invalid commandClass: CENTRAL_SCENE
2017-11-28 23:05:04 [log] [ManagerDrivers] [IDlock101] [0] Door Condition has changed: 2 binary array 10
(node:24972) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: invalid_type
(node:24972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2017-11-28 23:05:19 [log] [ManagerDrivers] [IDlock101] [0] node.CommandClass['COMMAND_CLASS_DOOR_LOCK'].on('report') arguments: { '0': { value: 3, name: 'DOOR_LOCK_OPERATION_REPORT' },
  '1':
   { 'Door Lock Mode (Raw)': <Buffer 00>,
     'Door Lock Mode': 'Door Unsecured',
     'Properties1 (Raw)': <Buffer 00>,
     Properties1:
      { 'Inside Door Handles Mode': 0,
        'Outside Door Handles Mode': 0 },
     'Door Condition (Raw)': <Buffer 03>,
     'Door Condition': 3,
     'Lock Timeout Minutes (Raw)': <Buffer fe>,
     'Lock Timeout Minutes': 254,
     'Lock Timeout Seconds (Raw)': <Buffer fe>,
     'Lock Timeout Seconds': 254 },
  '2': null }
2017-11-28 23:05:19 [log] [ManagerDrivers] [IDlock101] [0] Door Condition has changed: 3 binary array 11
(node:24972) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: invalid_type
2017-11-28 23:05:23 [log] [ManagerDrivers] [IDlock101] [0] node.CommandClass['COMMAND_CLASS_DOOR_LOCK'].on('report') arguments: { '0': { value: 3, name: 'DOOR_LOCK_OPERATION_REPORT' },
  '1':
   { 'Door Lock Mode (Raw)': <Buffer 00>,
     'Door Lock Mode': 'Door Unsecured',
     'Properties1 (Raw)': <Buffer 00>,
     Properties1:
      { 'Inside Door Handles Mode': 0,
        'Outside Door Handles Mode': 0 },
     'Door Condition (Raw)': <Buffer 02>,
     'Door Condition': 2,
     'Lock Timeout Minutes (Raw)': <Buffer fe>,
     'Lock Timeout Minutes': 254,
     'Lock Timeout Seconds (Raw)': <Buffer fe>,
     'Lock Timeout Seconds': 254 },
  '2': null }
2017-11-28 23:05:23 [log] [ManagerDrivers] [IDlock101] [0] Door Condition has changed: 2 binary array 10
(node:24972) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: invalid_type

After adding:

	process.on('unhandledRejection', (reason, p) => {
	  console.log('Unhandled Rejection at: Promise', p, 'reason:', reason);	//, 'stack:', reason.stack
	  // application specific logging, throwing an error, or other logic here
	});	
	

to app.js onInit() i get this info:
...
2017-11-28 23:07:04 [err] [ManagerDrivers] [IDlock101] [0] Invalid commandClass: CENTRAL_SCENE
2017-11-28 23:07:05 [log] [ManagerDrivers] [IDlock101] [0] Door Condition has changed: 2 binary array 10
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: invalid_type
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1040)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:938)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1345)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1330)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11) message: 'invalid_type' } } reason: { Error: invalid_type
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1040)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:938)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1345)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1330)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11) message: 'invalid_type' }
2017-11-28 23:07:10 [log] [ManagerDrivers] [IDlock101] [0] node.CommandClass['COMMAND_CLASS_DOOR_LOCK'].on('report') arguments: { '0': { value: 3, name: 'DOOR_LOCK_OPERATION_REPORT' },
  '1':
   { 'Door Lock Mode (Raw)': <Buffer 00>,
     'Door Lock Mode': 'Door Unsecured',
     'Properties1 (Raw)': <Buffer 00>,
     Properties1:
      { 'Inside Door Handles Mode': 0,
        'Outside Door Handles Mode': 0 },
     'Door Condition (Raw)': <Buffer 03>,
     'Door Condition': 3,
     'Lock Timeout Minutes (Raw)': <Buffer fe>,
     'Lock Timeout Minutes': 254,
     'Lock Timeout Seconds (Raw)': <Buffer fe>,
     'Lock Timeout Seconds': 254 },
  '2': null }
2017-11-28 23:07:10 [log] [ManagerDrivers] [IDlock101] [0] Door Condition has changed: 3 binary array 11
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: invalid_type
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1040)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:938)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1345)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1330)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11) message: 'invalid_type' } } reason: { Error: invalid_type
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1040)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:938)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1345)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1330)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11) message: 'invalid_type' }
2017-11-28 23:07:15 [log] [ManagerDrivers] [IDlock101] [0] node.CommandClass['COMMAND_CLASS_DOOR_LOCK'].on('report') arguments: { '0': { value: 3, name: 'DOOR_LOCK_OPERATION_REPORT' },
  '1':
   { 'Door Lock Mode (Raw)': <Buffer 00>,
     'Door Lock Mode': 'Door Unsecured',
     'Properties1 (Raw)': <Buffer 00>,
     Properties1:
      { 'Inside Door Handles Mode': 0,
        'Outside Door Handles Mode': 0 },
     'Door Condition (Raw)': <Buffer 02>,
     'Door Condition': 2,
     'Lock Timeout Minutes (Raw)': <Buffer fe>,
     'Lock Timeout Minutes': 254,
     'Lock Timeout Seconds (Raw)': <Buffer fe>,
     'Lock Timeout Seconds': 254 },
  '2': null }
2017-11-28 23:07:15 [log] [ManagerDrivers] [IDlock101] [0] Door Condition has changed: 2 binary array 10
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: invalid_type
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1040)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:938)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1345)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1330)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11) message: 'invalid_type' } } reason: { Error: invalid_type
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1040)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:938)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1345)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1330)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11) message: 'invalid_type' }

In the web interface only the door locked status is correct the other are just -
I hope this can be used to fix a possible problem (or maybe just inform me what I did wrong ;-) )

**Comment by MrZANE42** [comment]
![image](https://user-images.githubusercontent.com/7534100/33348004-048936f2-d495-11e7-88b0-ba6683d5f0ad.png)

![image](https://user-images.githubusercontent.com/7534100/33347965-e82f4c30-d494-11e7-969e-7bc5af7d15ba.png)

**Comment by MrZANE42** [comment]
This has been fixed in later release (By Ted)
